-- Vision's reviewed Phase B foundation. PostgreSQL is the sole transactional authority.
create table nodes (
  id text not null,
  owner_id text not null,
  identity_kind text not null,
  provider text not null,
  provider_node_id text not null,
  node_type text not null,
  domain text not null,
  domain_state text not null,
  privacy text not null,
  provenance text not null,
  lifecycle text not null,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  valid_from timestamptz not null,
  valid_to timestamptz,
  version integer not null,
  model_confidence integer,
  primary key (id),
  unique (id, owner_id),
  unique (id, owner_id, node_type),
  unique (owner_id, provider, provider_node_id),
  check (owner_id <> ''),
  check (provider <> ''),
  check (provider_node_id <> ''),
  check (identity_kind in ('provider', 'first_party', 'system')),
  check (node_type in ('event', 'task', 'note', 'commitment', 'recommendation', 'preference', 'policy', 'audit_event', 'person', 'calendar', 'source_artifact', 'alert_episode')),
  check (domain in ('school', 'work', 'personal', 'unresolved')),
  check (domain_state in ('confirmed', 'inferred', 'unresolved')),
  check ((domain = 'unresolved') = (domain_state = 'unresolved')),
  check (privacy in ('planning', 'private', 'restricted')),
  check (provenance in ('provider', 'user', 'system', 'model')),
  check (lifecycle in ('active', 'deleted', 'purged')),
  check (updated_at >= created_at),
  check (valid_to is null or valid_to > valid_from),
  check (version > 0),
  check ((domain_state = 'inferred') = (model_confidence is not null)),
  check (model_confidence is null or (model_confidence >= 0 and model_confidence <= 1000000))
);

create table events (
  node_id text not null,
  owner_id text not null,
  node_type text not null default 'event',
  provider text not null,
  provider_calendar_id text not null,
  provider_event_id text not null,
  provider_version text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  time_zone text not null,
  busy boolean not null,
  status text not null,
  recurrence_id text,
  title_envelope bytea,
  description_envelope bytea,
  attendees_envelope bytea,
  location_envelope bytea,
  meeting_link_envelope bytea,
  protected_key_version integer,
  primary key (node_id),
  unique (node_id, owner_id),
  unique (provider, provider_calendar_id, provider_event_id),
  foreign key (node_id, owner_id) references nodes (id, owner_id),
  foreign key (node_id, owner_id, node_type) references nodes (id, owner_id, node_type),
  check (provider <> ''),
  check (provider_calendar_id <> ''),
  check (provider_event_id <> ''),
  check (provider_version <> ''),
  check (node_type = 'event'),
  check (ends_at > starts_at),
  check (status in ('confirmed', 'tentative', 'cancelled')),
  check (protected_key_version is null or protected_key_version > 0)
);

create table edges (
  id text primary key,
  owner_id text not null,
  source_node_id text not null,
  source_node_type text not null,
  destination_node_id text not null,
  destination_node_type text not null,
  relation text not null,
  origin text not null,
  evidence text,
  confidence integer,
  lifecycle text not null,
  privacy text not null,
  valid_from timestamptz,
  valid_to timestamptz,
  version integer not null,
  foreign key (source_node_id, owner_id) references nodes (id, owner_id),
  foreign key (destination_node_id, owner_id) references nodes (id, owner_id),
  foreign key (source_node_id, owner_id, source_node_type) references nodes (id, owner_id, node_type),
  foreign key (destination_node_id, owner_id, destination_node_type) references nodes (id, owner_id, node_type),
  check (relation in ('event_in_calendar', 'task_from_source', 'note_about_event', 'commitment_for_person', 'recommendation_for_event', 'preference_for_policy', 'policy_governs_event', 'alert_episode_for_event')),
  check ((relation = 'event_in_calendar' and source_node_type = 'event' and destination_node_type = 'calendar') or (relation = 'task_from_source' and source_node_type = 'task' and destination_node_type = 'source_artifact') or (relation = 'note_about_event' and source_node_type = 'note' and destination_node_type = 'event') or (relation = 'commitment_for_person' and source_node_type = 'commitment' and destination_node_type = 'person') or (relation = 'recommendation_for_event' and source_node_type = 'recommendation' and destination_node_type = 'event') or (relation = 'preference_for_policy' and source_node_type = 'preference' and destination_node_type = 'policy') or (relation = 'policy_governs_event' and source_node_type = 'policy' and destination_node_type = 'event') or (relation = 'alert_episode_for_event' and source_node_type = 'alert_episode' and destination_node_type = 'event')),
  check (origin in ('provider', 'user', 'system', 'model')),
  check (lifecycle in ('proposed', 'confirmed', 'rejected', 'retracted')),
  check (privacy in ('planning', 'private', 'restricted')),
  check (confidence is null or (confidence >= 0 and confidence <= 1000000)),
  check (valid_to is null or (valid_from is not null and valid_to > valid_from)),
  check (version > 0)
);

create table audit_events (
  id text primary key,
  owner_id text not null,
  node_id text,
  actor_type text not null,
  action text not null,
  outcome text not null,
  provider text,
  error_category text,
  occurred_at timestamptz not null,
  foreign key (node_id, owner_id) references nodes (id, owner_id),
  check (owner_id <> '')
);

create table sync_checkpoints (
  id text primary key,
  owner_id text not null,
  provider text not null,
  provider_calendar_id text not null,
  sync_token_envelope bytea not null,
  key_version text not null,
  committed_at timestamptz not null,
  unique (owner_id, provider, provider_calendar_id),
  check (provider <> ''),
  check (provider_calendar_id <> ''),
  check (key_version <> '')
);

create table sync_channels (
  id text primary key,
  owner_id text not null,
  provider text not null,
  provider_calendar_id text not null,
  provider_channel_id text not null,
  provider_resource_id text not null,
  verification_token_envelope bytea not null,
  expires_at timestamptz not null,
  unique (owner_id, provider, provider_channel_id),
  check (provider <> ''),
  check (provider_calendar_id <> ''),
  check (provider_channel_id <> ''),
  check (provider_resource_id <> '')
);

create table operation_ledger (
  operation_id text primary key,
  owner_id text not null,
  provider text not null,
  provider_operation_id text not null,
  operation_kind text not null,
  status text not null,
  requested_at timestamptz not null,
  completed_at timestamptz,
  response_envelope bytea,
  unique (owner_id, provider, provider_operation_id),
  check (provider <> ''),
  check (provider_operation_id <> '')
);

create table recoverable_deletions (
  node_id text not null,
  owner_id text not null,
  deleted_at timestamptz not null,
  purge_after timestamptz not null,
  recovery_envelope bytea,
  primary key (node_id),
  foreign key (node_id, owner_id) references nodes (id, owner_id),
  check (purge_after > deleted_at)
);
